// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"fangaoxs.com/go-chat/environment"
	"fangaoxs.com/go-chat/internal/domain/user"
	"fangaoxs.com/go-chat/internal/infras/logger"
	"fangaoxs.com/go-chat/internal/storage/postgres"
)

// Injectors from wire.go:

func initServer(env environment.Env, logger2 logger.Logger) (*Server, error) {
	storage, err := postgres.New(env)
	if err != nil {
		return nil, err
	}
	userUser, err := user.New(env, storage)
	if err != nil {
		return nil, err
	}
	server, err := newServer(env, logger2, userUser)
	if err != nil {
		return nil, err
	}
	return server, nil
}
